import type { Metadata } from "next";
import LegalPage, { type LegalSection } from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How Elite Health and Community Services collects, uses, discloses and safeguards information.",
  alternates: { canonical: "/privacy-policy" },
};

const sections: LegalSection[] = [
  { id: "introduction", title: "Introduction", content: <p>Welcome to ELITE Health and Community Services. We are committed to protecting your personal information and your right to privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website [insert URL] (the “Site”). Please read this Privacy Policy carefully. If you do not agree with the terms of this Privacy Policy, please do not access the Site.</p> },
  { id: "collection", title: "Information We Collect", content: <><p>We may collect information about you in a variety of ways. The information we may collect on the Site includes:</p><h3>Personal Data</h3><p>Personally identifiable information, such as your name, shipping address, email address, and telephone number, that you voluntarily give to us when you register with the Site, make a purchase, or when you choose to participate in various activities related to the Site, such as online chat and message boards.</p><h3>Derivative Data</h3><p>Information our servers automatically collect when you access the Site, such as your IP address, your browser type, your operating system, your access times, and the pages you have viewed directly before and after accessing the Site.</p><h3>Financial Data</h3><p>Financial information, such as data related to your payment method (e.g., valid credit card number, card brand, expiration date) that we may collect when you purchase, order, return, exchange, or request information about our services from the Site.</p><h3>Mobile Device Data</h3><p>Device information, such as your mobile device ID, model, and manufacturer, and information about the location of your device, if you access the Site from a mobile device.</p></> },
  { id: "use", title: "How We Use Your Information", content: <><p>We use the information we collect or receive:</p><ul><li>To facilitate account creation and the logon process.</li><li>To process and manage purchases, orders, payments, and other transactions.</li><li>To improve our website and its offerings.</li><li>To respond to your requests and manage ongoing customer relations.</li><li>To send you newsletters, updates, and promotional offers.</li><li>To comply with legal obligations and to enforce our terms, conditions, and policies.</li></ul></> },
  { id: "disclosure", title: "Disclosure of Your Information", content: <><p>We may share information we have collected about you in certain situations. Your information may be disclosed as follows:</p><h3>By Law or to Protect Rights</h3><p>If we believe the release of information about you is necessary to respond to legal process, to investigate or remedy potential violations of our policies, or to protect the rights, property, and safety of others, we may share your information as permitted or required by any applicable law, rule, or regulation.</p><h3>Third-Party Service Providers</h3><p>We may share your information with third parties that perform services for us or on our behalf, including payment processing, data analysis, email delivery, hosting services, customer service, and marketing assistance.</p><h3>Business Transfers</h3><p>We may share or transfer your information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.</p></> },
  { id: "cookies", title: "Cookies and Other Tracking Technologies", content: <p>We may use cookies, web beacons, tracking pixels, and other tracking technologies on the Site to help customize the Site and improve your experience.</p> },
  { id: "security", title: "Security of Your Information", content: <p>We use administrative, technical, and physical security measures to help protect your personal information. While we have taken reasonable steps to secure the personal information you provide to us, please be aware that despite our efforts, no security measures are perfect or impenetrable, and no method of data transmission can be guaranteed against any interception or other types of misuse.</p> },
  { id: "children", title: "Policy for Children", content: <p>We do not knowingly solicit information from or market to children under the age of 13. If we learn that we have collected personal information from a child under age 13 without verification of parental consent, we will delete that information as quickly as possible.</p> },
  { id: "rights", title: "Your Privacy Rights", content: <p>Depending on your location, you may have certain rights regarding your personal information. These may include the right to access, correct, delete, or restrict the use of your personal information. To exercise these rights, please contact us using the contact information provided below.</p> },
  { id: "changes", title: "Changes to This Privacy Policy", content: <p>We may update this Privacy Policy from time to time in order to reflect changes in our practices or for other operational, legal, or regulatory reasons. We encourage you to review this Privacy Policy periodically to be informed of how we are protecting your information.</p> },
  { id: "contact", title: "Contact Us", content: <><p>If you have questions or comments about this Privacy Policy, please contact us at:</p><p><strong>Elite Health and Community Services</strong><br /><a href="mailto:admin@elitehcs.com.au">admin@elitehcs.com.au</a><br /><a href="tel:+61422911216">+61 422 911 216</a></p><p><strong>Note:</strong> Ensure this privacy statement complies with relevant laws such as GDPR, CCPA, or any other applicable privacy regulations. Consulting with a legal professional to customize it to your specific needs is highly recommended.</p></> },
];

export default function PrivacyPolicyPage() {
  return <LegalPage eyebrow="Your information" title="Privacy Policy" effectiveDate="20.08.2024" intro="How Elite Health and Community Services collects, uses, discloses and safeguards information when you use the website." sections={sections} />;
}
