import type { Metadata } from "next";
import LegalPage, { type LegalSection } from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description: "Terms and conditions governing use of the Elite Health and Community Services website.",
  alternates: { canonical: "/terms-and-conditions" },
};

const sections: LegalSection[] = [
  { id: "acceptance", title: "Acceptance of Terms", content: <p>By using the Site, you affirm that you are at least 18 years old or, if under 18, are accessing the Site with the consent of a parent or guardian who agrees to these Terms on your behalf. Your use of the Site constitutes your agreement to these Terms.</p> },
  { id: "services", title: "Services Provided", content: <p>Elite Health and Community Services offers a variety of health and community services, including [list key services, e.g., disability support, community care, mental health services, etc.]. These services are provided according to specific service agreements that clients enter into with us. The information provided on the Site is for general informational purposes only and does not constitute medical, legal, or other professional advice.</p> },
  { id: "obligations", title: "User Obligations", content: <><p>When using our Site, you agree to:</p><ul><li>Provide accurate, current, and complete information when prompted or required.</li><li>Use the Site in a manner consistent with all applicable laws and regulations.</li><li>Not engage in any behavior that could harm the Site, its users, or the services provided.</li><li>Not attempt to gain unauthorized access to any part of the Site, other accounts, or systems connected to the Site.</li></ul></> },
  { id: "intellectual-property", title: "Intellectual Property Rights", content: <p>All content, including but not limited to text, images, logos, graphics, and software, available on the Site is the property of Elite Health and Community Services or its licensors and is protected by applicable intellectual property laws. You are granted a limited, non-exclusive, non-transferable license to access and use the Site for personal, non-commercial purposes. You may not copy, reproduce, distribute, modify, or create derivative works from any part of the Site without our prior written consent.</p> },
  { id: "user-content", title: "User-Generated Content", content: <p>If you submit any content, such as reviews, comments, or suggestions, to the Site, you grant us a non-exclusive, royalty-free, perpetual, and worldwide license to use, display, distribute, and modify such content. You represent and warrant that you own or have the necessary rights to submit the content and that the content does not infringe any third-party rights.</p> },
  { id: "privacy", title: "Privacy", content: <p>Your use of the Site is also governed by our <a href="/privacy-policy">Privacy Policy</a>, which explains how we collect, use, and protect your personal information. By using the Site, you agree to the terms of the Privacy Policy.</p> },
  { id: "third-party", title: "Third-Party Links", content: <p>The Site may contain links to third-party websites or services that are not owned or controlled by Elite Health and Community Services. We are not responsible for the content, privacy policies, or practices of any third-party websites or services. You access these links at your own risk, and we recommend that you review the terms and conditions and privacy policies of any third-party websites you visit.</p> },
  { id: "disclaimers", title: "Disclaimers", content: <><p>The Site and its content are provided “as is” and “as available” without any warranties of any kind, either express or implied. To the fullest extent permitted by law, we disclaim all warranties, express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement.</p><p>We do not warrant that the Site will be uninterrupted, error-free, secure, or free of viruses or other harmful components. You agree that your use of the Site is at your own risk.</p></> },
  { id: "liability", title: "Limitation of Liability", content: <p>To the maximum extent permitted by law, in no event shall Elite Health and Community Services, its affiliates, directors, employees, or agents be liable for any direct, indirect, incidental, special, or consequential damages resulting from your use of the Site or any of its content, even if we have been advised of the possibility of such damages.</p> },
  { id: "indemnification", title: "Indemnification", content: <p>You agree to indemnify, defend, and hold harmless Elite Health and Community Services, its affiliates, directors, employees, and agents from and against any and all claims, damages, losses, liabilities, and expenses (including reasonable attorneys’ fees) arising out of or in connection with your use of the Site, your violation of these Terms, or your violation of any rights of a third party.</p> },
  { id: "changes", title: "Changes to These Terms", content: <p>We reserve the right to modify or update these Terms at any time. Any changes will be effective immediately upon posting on the Site. Your continued use of the Site after any changes to the Terms constitutes your acceptance of the new terms.</p> },
  { id: "law", title: "Governing Law", content: <p>These Terms shall be governed by and construed in accordance with the laws of [Your State/Country], without regard to its conflict of law principles. You agree to submit to the exclusive jurisdiction of the courts located within [Your Jurisdiction] to resolve any legal matter arising from these Terms or your use of the Site.</p> },
  { id: "termination", title: "Termination", content: <p>We reserve the right, in our sole discretion, to terminate or suspend your access to the Site, without notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties, or for any other reason.</p> },
  { id: "contact", title: "Contact Information", content: <><p>If you have any questions about these Terms, please contact us at:</p><p><strong>Elite Health and Community Services</strong><br /><a href="mailto:enquiry@elitehcs.com.au">enquiry@elitehcs.com.au</a><br /><a href="tel:+61415427649">+61 415 427 649</a></p></> },
];

export default function TermsPage() {
  return <LegalPage eyebrow="Using our website" title="Terms & Conditions" effectiveDate="20.08.2024" intro="Welcome to Elite Health and Community Services. By accessing or using our website “elitehcs.com”, you agree to comply with and be bound by the following terms and conditions (“Terms”). If you do not agree with these Terms, please do not use the Site." sections={sections} />;
}
